steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-east1-docker.pkg.dev/nih-nci-dceg-druss/crtest','.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'crtest', '--image', 'us-east1-docker.pkg.dev/nih-nci-dceg-druss/crtest','--region', 'us-east1', '--platform', 'managed','--allow-unauthenticated']

