steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-east1-docker.pkg.dev/nih-nci-dceg-druss/test1/rcloudruntest','.']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-service', '--image', 'us-east1-docker.pkg.dev/nih-nci-dceg-druss/test1/rcloudruntest','--region', 'us-east1', '--platform', 'managed']

